# Generated by Django 4.2 on 2023-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='type',
            field=models.CharField(choices=[(1, 'IT'), (2, 'Non IT'), (3, 'Phone Mobile')], default='', max_length=100),
        ),
    ]
