# Generated by Django 4.2 on 2023-04-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_companymodel_about_alter_companymodel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non IT'), ('Phone Mobile', 'Phone Mobile')], max_length=100),
        ),
    ]
